# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Prepull to main checks

on:
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -U pylint
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Run Lint
          run: pylint BrainBlazeInfoGraphic.py BrainBlazeAnalyser.py DailyBrainBlaze.py google_access_lib.py

  type_checks:
    runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"

                  - name: Install dependencies
                    run: |
                      python -m pip install --upgrade pip
                      python -m pip install -U mypy
                      python -m pip install -U types-python-dateutil
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

                  - name: Run MyPy
                    run: mypy BrainBlazeInfoGraphic.py BrainBlazeAnalyser.py DailyBrainBlaze.py google_access_lib.py


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate Report
      run: |
        python BrainBlazeInfoGraphic.py -youtubeapikey ${{ secrets.YOUTUBE_API_KEY }} -twitter_consumer_key ${{ secrets.TWITTER_CONSUMER_KEY}} -twitter_consumer_secret ${{ secrets.TWITTER_CONSUMER_SECRET}} -twitter_access_token ${{ secrets.TWITTER_ACCESS_TOKEN}} -twitter_access_secret ${{ secrets.TWITTER_ACCESS_SECRET}} -test_mode -test_mode_dm_user_name ${{ secrets.TEST_MODE_DM_TARGET}}
        python DailyBrainBlaze.py -youtubeapikey ${{ secrets.YOUTUBE_API_KEY }} -twitter_consumer_key ${{ secrets.TWITTER_CONSUMER_KEY}} -twitter_consumer_secret ${{ secrets.TWITTER_CONSUMER_SECRET}} -twitter_access_token ${{ secrets.TWITTER_ACCESS_TOKEN}} -twitter_access_secret ${{ secrets.TWITTER_ACCESS_SECRET}} -test_mode

